### ISSUE TITLE
CSS file with variable placeholders breaks at import

### ISSUE THREAD

**Issue by seaneble** [contao/core#7448]
I created a CSS file externally and would like to import it into Contao 3.4.RC1. I used the calc() function of CSS extensively:

```css
.grid1  { width:calc(100%/12 - 20*10px); }
```

I am also making use of the Contao variables defined in my theme. The above code actually looks like

```css
.grid1  { width:calc(100%/12 - 20*$margin); }
```

Both syntactical constructs get mangled during import into Contao. What is ending up in the backend is this:

```css
.grid1  { width:10012-20cc%mrin; }
```

I think the problem is that Contao somehow tries to map the margin into the corresponding database field for the width, while it should actually go into the user defined code field.

Also, it would be convenient if Contao could keep variables defined in the CSS file. Currently, they are simply deleted when using syntax like:

```css
.class { margin: $margin; }
```
