### ISSUE TITLE
Remove the class conflict (invisible) with html5-boilerplate

### ISSUE THREAD

**Issue by lionel-m** [contao/core#7541]
html5-boilerplate use `.hidden`, `.visuallyhidden`, `.invisible` for the three main methods used to remove the visibility of an element.

The `.invisible` class of Contao is ~ equivalent to the `.visuallyhidden` class of html5-boilerplate. This can be a source of error if the file `main.css` of html5-boilerplate is not modified. In this case the following code is used:

```CSS
.invisible {
visibility: hidden;
}
```
html5-boilerplate is popular and we should consider changing the `.invisible` class of Contao with `.visuallyhidden`and this class name also better reflects the goal.

Do we have the opportunity to change this class name with Contao 4?

**Comment by Toflar** [comment]
https://packagist.org/packages/toflar/contao-css-class-replacer

**Comment by lionel-m** [comment]
Thank you for the info. Nice extension!
However, I think it's a good thing to change it for all in Contao for the reasons explained in my first comment.

**Comment by frontendschlampe** [comment]
I also think, it will be a good idea to change it!

**Comment by leofeyer** [comment]
How do the other CSS frameworks such as Foundation and Bootstrap name the corresponding classes? I doubt that there is a "one size fits all" solution here.

**Comment by lionel-m** [comment]
> How do the other CSS frameworks such as Foundation and Bootstrap name the corresponding class? I doubt that there is a "one size fits all" solution here.

That's right e.g. suitcss: `u-hiddenVisually`, Bootstrap `sr-only`, Foundation `element-invisible`, etc. But this change is to avoid an issue regarding accessibility in the case where html5-boilerplate is used.

If we have to replace the current name with a new one, I propose to use `visuallyhidden` because it gives a clear information on its purpose.

**Comment by aschempp** [comment]
To me, "visuallyhidden" is way more like "visibility: hidden" than "invisible" is…=

**Comment by frontendschlampe** [comment]
The problem is, that every framework uses other functionality. In Bootstrap they use

```css
.invisible {
	display: none !important;
	visibility: hidden;
}

.visuallyhidden {
	border: 0;
	clip: rect(0 0 0 0);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute;
	width: 1px;
}

.visuallyhidden.focusable:active, .visuallyhidden.focusable:focus {
	clip: auto;
	height: auto;
	margin: 0;
	overflow: visible;
	position: static;
	width: auto;
}
```

But the usage of ```visuallyhidden```is in Bootstrap and HTML5Boilerplate the same, so for these two frameworks it would be great if we change it. Maybe @MoniqueHahnefeld can check for Foundation and @MacKP for YAML, but as I could see, they use complete other classes: ```.skip```in Foundation and ```.ym-skip```or ```.ym-hideme```in YAML.
