### ISSUE TITLE
Backend: Pagination der Listen ziemlich unhandlich

### ISSUE THREAD

**Issue by mathContao** [contao/core#7956]
Sind viele News oder Events im Backend vorhanden, werden die Listen auf mehrere Seiten umgebrochen. Jedoch ist das wählen der Seitenzahlen mit der Maus ziemlich schwierig, weil die Linkfläche sehr klein ist.

![screenshot1](https://cloud.githubusercontent.com/assets/1645099/9049821/c6941280-3a46-11e5-8186-e1a8dd73db75.JPG)

Die Flächen farbig hervorgehoben (rot = &lt;a href=""&gt;-Element; blau= &lt;li&gt;-Element):
![screenshot2](https://cloud.githubusercontent.com/assets/1645099/9049828/d85527de-3a46-11e5-9d6c-6d3c816daeed.JPG)
Das &lt;li&gt;-Element (blau) hat sogar noch ein padding-right=3px. Diese 3 Pixel würden dem &lt;a href=""&gt;-Element (rot) in der Breite deutlich mehr helfen und die Bedienung leichter machen. Die Lücken zwischen den &lt;li&gt;-Elementen (blau) kann ich mir nicht erklären, könnten vielleicht auch noch mit für eine größere Linkfläche genutzt werden.

**Comment by Aybee** [comment]
Die Lücken kommen daher, weil die LIs display:inline sind.

Als erstes müsste dem Container div.pagination das Padding oben und unten genommen werden, das kann man nachher den As und dem span.current geben (auch dem .pagination p).

Um die UL rechtsbündig auszurichten kann man ihm das width:60% nehmen und mit max-width ersetzen (falls überhaupt benötigt). text-align:right braucht es dann nicht mehr, weil die LIs späer nicht mehr inline sein werden.

Jetzt können die LIs auf float:left gesetzt werden, sie sind damit auch direkt display block. Padding für LIs entfernen.

Zum Schluss dann den SPANs und As display:block geben (nicht unbedingt nötig aber sauberer, falls man noch weiter formatieren möchte) und mit dem Padding die sensitive Klick-Fläche einstellen.
![system_log_-_contao_open_source_cms_3 5_-_2015-08-04_16 45 02](https://cloud.githubusercontent.com/assets/1143013/9063563/57696c7a-3ac8-11e5-88ee-1178c802db01.png)

**Comment by mathContao** [comment]
Das sieht gut aus :) :+1:

**Comment by Aybee** [comment]
Hier zum ausprobieren mit Stylish https://addons.mozilla.org/de/firefox/addon/stylish/?src=ss o.ä.

```css
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document regexp(".*demo\.contao\.org/contao/main\.php.*") {
  .pagination {
    padding-top: 0;
    padding-bottom: 0;
  }
  .pagination p {
    padding-top: 5px;
    padding-bottom: 5px;
  }
  .pagination ul {
    width: auto;
    max-width: 60%;
  }
  .pagination li {
    float: left;
    padding: 0;
  }
  .pagination span,
  .pagination a {
    display: block;
    padding: 5px;      
  }
  .pagination a:hover {
    background-color: #fff;      
  }
}
```
