### ISSUE TITLE
[3.5.2] Hook für LessParser

### ISSUE THREAD

**Issue by Sioweb** [contao/core#7985]
Guten Tag,

in meinen Css/Less Dateien verwende ich gerne width: calc(100% - 45px); woraus der Less-Parser dann 55% macht weil er nicht strictMath verwendet. 

Ich würde vorschlagen diese Option generell zu aktivieren, oder besser einen Hook in die entsprechende Methode zu schreiben, damit der Parser angepasst werden kann:

- system/modules/core/library/Contao/Combiner.php
- Zeile 331 / Methode handleScssLess

```
$arrOptions = array(
	// 'strictMath' => true,
	'compress' => !\Config::get('debugMode'),
	'import_dirs' => array(TL_ROOT . '/' . $strPath => $strPath)
);

if (isset($GLOBALS['TL_HOOKS']['handleScssLess']) && is_array($GLOBALS['TL_HOOKS']['handleScssLess'])) {
	foreach ($GLOBALS['TL_HOOKS']['handleScssLess'] as $callback) {
	  $this->import($callback[0]);
	  $arrOptions = $this->$callback[0]->$callback[1]($arrOptions);
	}
}
```

Generell wäre es nicht verkehrt die Vendoren konfigurieren zu können, was meint ihr? Damit die Optionen nicht verloren gehen könnte man mit array_merge arbeiten.

Danke & Grüße
Sascha

**Comment by leofeyer** [comment]
Bist Du sicher, dass die "strictMath"-Option hier richtig ist und nicht die "strictUnits"-Option?

**Comment by asaage** [comment]
escape mit __~__
ich denke der korrekte Output im css wird sonst weder mit strictMath noch mit strictUnits funktionieren
```less
div.foo {
    width: calc(~"100% - 45px");
}
```

**Comment by Sioweb** [comment]
StrictMath funktioniert bei mir so. Ich habe Units noch nie probiert und Tilde funktioniert generell, aber ist für mich aktuell keine Option weil mein Argument ist "Du kannst Less ganz einfach wie CSS schreiben.", was mit Tilde einfach nicht gegeben ist.

**Comment by asaage** [comment]
http://lesscss.org/usage/#command-line-usage-strict-math

gut - wirst wohl recht haben mit _StrictMath = on_.
andernfalls bleibt noch die Option den Parser zu umgehen und die externen stylesheets durch Import zu internen zu machen.

**Comment by Sioweb** [comment]
Dazu müsste ich die Datei soweit ich weiß nur mit .css abspeichern. Wir wollen ja nicht generell auf Less verzichten und wegen calc() eine neue Datei zu erstellen kann ich niemandem verkaufen.

Die Option muss ja nicht standardmäßig in Contao drin sein, aber ich würde sie gerne Update-Sicher einbauen.

**Comment by asaage** [comment]
gut - verstehe.
Ich hab mich auch ehrlichgesagt noch nicht eingehend mit less in verbindung mit contao beschäftigt sondern mich mit blindem Aktionismus auf das "feedback required" Label gestürzt.

**Comment by leofeyer** [comment]
Ich habe die Option testweise mal aktiviert, allerdings löst er den Code nicht so vollständig auf, wie es in der [Doku](http://lesscss.org/usage/#command-line-usage-strict-math) beschrieben ist..

```less
// LESS
div.foo {
    width: calc(100% - 45px);
}
div.foobar {
  width: calc(100% - (10px  - 5px));
  height: (100px / 4px);
  font-size: 1 / 4;
}
```

```css
/* Ausgabe ohne strictMath */
div.foo{width: calc(55%)}div.foobar{width: calc(95%);height: 25px;font-size: .25}

/* Ausgabe mit strictMath */
div.foo{width: calc(100% - 45px)}div.foobar{width: calc(100% - (10px - 5px));height: 25px;font-size: 1 / 4}

/* Ausgabe "echter" LESS-Parser */
div.foo{width: calc(100% - 45px)}div.foobar{width: calc(100% - 5px);height: 25px;font-size: 1/4}
```
