### ISSUE TITLE
Remove invisible CSS from BE CE preview

### ISSUE THREAD

**Issue by Aybee** [contao/core#8057]
Online Demo:
Einem Textelement (z.B. Articles » Home CE ID 1) die CSS-Klasse **invisible** geben.
Speichern und zurück gehen. Der Inhalt ist nicht sichtbar.

Ich benutze die Klasse **invisible** schon mal öfters für Screereader Elemente, möchte sie aber trotzdem im BE in der Vorschau sehen. Man könnte das z.B. so einstellen:

``` css
.limit_height .invisible {
  clip: auto;
  height: auto;
  position: static;
  width: auto;
}
```

Oder was denkt ihr, macht das Sinn, dass sie auch in der BE Vorschau unsichtbar sind? Ich denke nein.
