### ISSUE TITLE
Links in TinyMCE mit CSS-Klasse

### ISSUE THREAD

**Issue by Anke** [contao/core#8622]
Es wäre schön, wenn man beim Einfügen eines Links im TinyMCE ein Feld CSS-Klasse hätte, z.B. um interne und externe Links etc. bequem unterschiedlich zu stylen.

**Comment by asaage** [comment]
Machs doch mit reinem CSS.
Die externen Links haben immer http am Anfang des href's - die internen nicht.
Das lässt sich sogar auf ```mailto``` Links ausweiten

```css
/* Links that start with "http" */
a[href^=http] { background-color:red; }

/* Links that don't start with "http" */
a:not([href^=http]) { background-color:lightgreen; }

/* Links that contain a specific domain name */
a[href*=example\.com] { background-color:lightblue; }
```
```html
<a href="http://google.com/">external</a>
<a href="example.html">internal</a>
<a href="http://example.com">example.com</a>
```
