### ISSUE TITLE
file info iframe does not get enough height

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8631]
If you view the info of a file in the file manager for a non-image file, the iframe won't always be high enough to view all infos without scrolling (depending on the length of the infos). Happens in Contao 3.5 and 4.3:

![screen shot 2017-01-23 at 10 43 37](https://cloud.githubusercontent.com/assets/4970961/22198953/17ed2ab2-e159-11e6-9206-1985b2054d1d.png)

![screen shot 2017-01-23 at 10 44 13](https://cloud.githubusercontent.com/assets/4970961/22198952/17ec4688-e159-11e6-852f-3b2e6f461c43.png)

It seems the iframe is only automatically resized when viewing the info of images.

**Comment by asaage** [comment]
I think thats because the modal tries to fit itself on the page.

in addition to that i get an anoying overflow-x scrollbar in chrome.

![image](https://cloud.githubusercontent.com/assets/4138336/22199977/6cb34faa-e15d-11e6-9e2f-6670012e5a8c.png)

simplemodal.min.css
```css
 .simple-modal .simple-modal-body div.contents {
    overflow-y: hidden;
    overflow-x: scroll;  /* should be auto */
}
```
