### ISSUE TITLE
responsive.css breaks Google Maps

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8651]
The `responsive.css` of the Contao CSS framework includes the following style:
```css
img {
    max-width:100%;
    height:auto;
}
```
This however breaks Google Maps on the site. If you do not remove it or override it with your own style, any Google Map on your site will not work and simply stay gray (without any error message whatsoever).

This problem appears frequently on the Community forum. I am not sure if this is something that has to be or should be fixed by Contao. Just want to bring it up here. May be by default the style shouldn't be that general. Or something like 
```css
/* prevent breaking of Google Maps (see #8651) */
.gm-style img {
    max-width:none;
}
```
could be included at the end of the current `responsive.css`.
