### ISSUE TITLE
Contao 3.5.30 adds "blink" CSS class to body

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8801]
The new rendering engine of Google Chrome (a fork of webkit) is called _Blink_. Thus a change was introduced in 759c57b46292ff402eef9f0185ea31d574a7bbab to add `blink` to the `<body>` instead of `webkit` for Google Chrome.

However, some users had the following CSS:
```css
.blink {
    text-decoration: blink
}
```
So after updating to Contao `3.5.30`, their websites started blinking 😁 
https://community.contao.org/de/showthread.php?68451-Website-blinkt-in-Google-Chrome-st%C3%A4ndig

I don't expect this to be changed, mostly just posting it here in case anyone else stumbles over this issue.

**Comment by leofeyer** [comment]
According to the specifications, `text-decoration: blink` should have no effect in Chrome:

https://developer.mozilla.org/de/docs/Web/CSS/text-decoration#Browser_Kompatibilität

At least on macOS with Chrome 62, it had no effect. Couldn't test Chrome on Windows.

> I don't expect this to be changed,

We can't change it anyway.

**Comment by bytehead** [comment]
In the mentioned example, there is even some css-animation stuff:
```css
.blink {
    text-decoration: blink;
    -webkit-animation-name: blinker;
    -webkit-animation-duration: 1.8s;
    -webkit-animation-iteration-count: infinite;
    -webkit-animation-timing-function: ease-in-out;
    -webkit-animation-direction: alternate;
}

@keyframes blinker {
0% {
    opacity: 1.0;
}
100% {
    opacity: 0.0;
}
```
It does not come from `text-decoration: blink`.
